[package]
name = "kitchensink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

observe_instrument = { path = "../observe_instrument" }
observe_api = { path = "../observe_api" }
log = "0.4.19"
