[package]
name = "dylibso-observe-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
wasmtime = { version = ">= 8", optional = true }
wasmtime-wasi = { version = ">= 8", optional = true }
wasmer = { version = "3.1", optional = true }
wasmer-wasi = { version = ">= 3.1", optional = true }
tokio = { version = "1", features = ["sync", "rt-multi-thread", "macros"] }
rand = "0"
modsurfer-demangle = { git = "https://github.com/dylibso/modsurfer" }
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_tuple = "0"
ureq = "2"
url = "2"
wasmparser = "0.107.0"

[features]
default = ["wasmtime"]
# default = ["wasmer"]
wasmtime = ["dep:wasmtime", "dep:wasmtime-wasi"]
wasmer = ["dep:wasmer"]

[[example]]
name = "otel-stdout-wasmer"
path = "examples/otel-stdout-wasmer.rs"
required-features = ["wasmer", "wasmer-wasi"]
