[package]
name = "dylibso-observe-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
wasmtime = "8.0.0"
wasmtime-wasi = "8.0.0"
tokio = { version = "1.28.1", features = ["sync", "rt-multi-thread", "macros"] }
rand = "0.8.5"
modsurfer-demangle = { git = "https://github.com/dylibso/modsurfer" }
log = "0.4.18"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = "2.6.2"
